### ISSUE TITLE
Error: Cannot read property 'name' of undefined (nimble-picker.js:579)

### ISSUE THREAD

**Issue by nicreichert** [missive/emoji-mart#192] opened 2018-05-21 14:21 UTC
Hello,

Recently my project started having the above mentioned error when I try and render the `Picker` component.

The component is being rendered by a container that hasn't been changed in weeks, nevertheless it started happening quite out of the blue. 

I'm not doing any magic, just simply rendering the `Picker` like this:

```js
<Picker
  onClick={this.addEmoji}
  style={PickerStyle}
  perLine={9}
  showSkinTones={false}
  title=""
/>
```

Here's the full error stack:

<img width="440" alt="screen shot 2018-05-21 at 16 23 58" src="https://user-images.githubusercontent.com/4841711/40312538-67d9b4b4-5d13-11e8-80d4-9c11238602c7.png">

Has anyone seen this before?

Thanks for your help in advance.

**Comment by pawelsamsel** [comment] 2018-08-26 19:40
Hey, any luck with this? I have got a similar issue now.

**Comment by nolanlawson** [comment] 2019-03-08 02:57
Does this bug still repro in the latest version? Do you have some code to help us reproduce it?

**Comment by nolanlawson** [comment] 2019-03-10 17:08
I attempted to reproduce this by pasting the code above into the storybook, but was not able (https://github.com/missive/emoji-mart/commit/26530f4b0c23f559ea8d63104529da910245d587). Does this only happen in dev mode? I wasn't able to find any reference to `eval()` in `nimble-picker.js`, but perhaps it's related to a dev mode config.

**Comment by nolanlawson** [comment] 2019-03-16 22:57
Closing as this bug might be a duplicate of #201, which is fixed. Please reopen if this still reproduces.

**Closed by nolanlawson** 2019-03-16 22:57 UTC
Labels: bug
