### ISSUE TITLE
Version 2.11.2 gives error "Module not found: Error: Can't resolve 'babel-runtime/core-js/....'"

### ISSUE THREAD

**Issue by denver-s** [missive/emoji-mart#403] opened 2020-01-07 09:59 UTC
I get many errors such as this one, since version 2.11.2 (I had to downgrade to 2.11.1):

```
ERROR in ./node_modules/emoji-mart/dist/utils/store.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/json/stringify' in 'C:\...\node_modules\emoji-mart\dist\utils'
 @ ./node_modules/emoji-mart/dist/utils/store.js 7:17-64
 @ ./node_modules/emoji-mart/dist/index.js
```

**Comment by saltire** [comment] 2020-01-14 16:56
Duplicate of https://github.com/missive/emoji-mart/issues/393?

**Comment by EtienneLem** [comment] 2022-07-27 15:26
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Closed by EtienneLem** 2022-07-27 15:26 UTC
