### ISSUE TITLE
Virtualize or lazy-render the list of emoji

### ISSUE THREAD

**Issue by JustinDrake** [missive/emoji-mart#72] opened 2017-05-02 20:48 UTC
At the moment it seems all images are rendered at the same time during load. My gut feel is performance would improve drastically if images where lazily rendered when scrolling. (See for example this library https://github.com/dinbror/blazy.)

**Comment by vkartaviy** [comment] 2017-12-08 23:03
Btw - **Slack** uses https://github.com/bvaughn/react-virtualized for that https://slack.engineering/rebuilding-slacks-emoji-picker-in-react-bfbd8ce6fbfe?gi=e7eb80a7d19f

**Comment by nolanlawson** [comment] 2019-03-16 23:10
Looks like a duplicate of #6

**Closed by nolanlawson** 2019-03-16 23:10 UTC
Labels: enhancement
