### ISSUE TITLE
"Attempted to assign to readonly property"

### ISSUE THREAD

**Issue by philraj** [missive/emoji-mart#200] opened 2018-07-06 14:55 UTC
I got this curious error logged in our app's Sentry:  

![image](https://user-images.githubusercontent.com/16470658/42385341-7cfc6bbe-810a-11e8-9d75-711a5f52d9f4.png)

Platform: Mobile Safari 11, iOS 11.2.5
(Emoji-mart version 2.6.1)

Any idea what's going on here?

**Comment by philraj** [comment] 2018-07-06 15:11
Not sure if tangentially related, but here's another error thrown by the same line:

![image](https://user-images.githubusercontent.com/16470658/42386346-42d5f15a-810d-11e8-9757-4f75303d6a25.png)

**Comment by nolanlawson** [comment] 2019-03-08 02:54
Is this only an iOS bug? Does it consistently reproduce?

**Comment by nolanlawson** [comment] 2019-03-16 23:17
It's not clear to me how to reproduce this bug or what conditions cause it to arise. It looks like "Sentry" is [error-reporting software](https://sentry.io/welcome/), so I assume the error report would say what browser/OS this occurred on, which would help us debug.

Please reopen if there is more information you can provide. Closing for now.

**Closed by nolanlawson** 2019-03-16 23:17 UTC
Labels: bug

**Comment by philraj** [comment] 2019-03-17 05:16
Looks like it was only on mobile Safari 11, but our production system hasn't seen this exact error in 8 months.
