### ISSUE TITLE
Switch to Emojibase for data source

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#384] opened 2019-12-04 17:55 UTC
Given that your current data source emoji-mart seems to be not well-maintained and lacking behind Unicode standards (see https://github.com/iamcal/emoji-data/issues/145 / https://github.com/missive/emoji-mart/issues/269), maybe it would be a good idea to look into alternatives?

https://milesj.gitbook.io/emojibase/ seems to be a good one.

* it uses the official data
* Unicode 12 emojis
* Emoticon short codes even
* it would also solve https://github.com/missive/emoji-mart/issues/303 as it has translated emoji terms etc.

Only con point:
* does not have any images as far as I see, but maybe you could combine the sources? (for native emojis it would be more than enough)

**Comment by nolanlawson** [comment] 2019-12-21 19:04
At some point we will need to solve #269, yes. Every year the current emoji set gets more and more out of date.

OTOH this issue seems to be a duplicate of #269, so maybe we should keep discussion there? Switching to another emoji data set is definitely an option IMO.

**Closed by nolanlawson** 2019-12-21 19:04 UTC
Labels: enhancement

**Comment by rugk** [comment] 2022-04-19 09:32
I'd like to bring this up again. Emojibase seems to be way more elaborate. Also the doc is way better as far as I see.

They have their own website after all: https://emojibase.dev/

And they included things like translations already, see https://github.com/iamcal/emoji-data/issues/148#issuecomment-673928262 (which is our issue https://github.com/missive/emoji-mart/issues/303).

So in the long run, switching to that emoji lib may be beneficial and make it easier to maintain this emoji picker here.
