### ISSUE TITLE
Search not updating

### ISSUE THREAD

**Issue by jynnie** [missive/emoji-mart#435] opened 2020-06-19 23:45 UTC
Search is not updating on input. I'm not sure why? It's in a styled component; but even when I take it out it doesn't update. I don't get any errors in console.

![2020-06-19 16 43 16](https://user-images.githubusercontent.com/7284723/85186144-5bcfaf80-b265-11ea-8ef9-4db5a6939182.gif)

**Comment by jynnie** [comment] 2020-06-19 23:47
Update: It eventually filters, but after a very long time (approx. a minute).

![image](https://user-images.githubusercontent.com/7284723/85186192-a6e9c280-b265-11ea-9839-3ef7deb77c15.png)

**Comment by VickyXXXXXX** [comment] 2020-06-23 16:45
I have similar issue and i tested it on a few devices.

OS | Processor | Graphic Card | Browser | Status
-- | -- | -- | -- | --
macOS High Sierra v10.13.6 | 3.06GHz Intel Core i3 | ATI Radeon HD 4670 [256 MB] | Chrome 83.0 | Reproducing
macOS High Sierra v10.13.6 | 3.06GHz Intel Core2 Duo | NVIDIA GeForce 9400 [256 MB] | Chrome 83.0 | Reproducing
MacOSHigh Sierra v10.13.6 | 3.06GHz Intel Core i3 | ATI Radeon HD 4670 [256 MB] | Chrome 83.0 | Reproducing
MacOSHigh Sierra v10.13.6 | 3.06GHz Intel Core2 Duo | NVIDIA GeForce 9400 [256 MB] | Chrome 83.0 | Reproducing
OS X El Capitan v10.11.6 | 2.4 GHz Intel Core2 Duo | ATI Radeon HD 2400 XT[128 MB] | Chrome 83.0 | Reproducing
macOS High Sierra v10.13.6 | 2.5 GHz Intel Core i5 | ATI Radeon HD 6750M [512 MB] | Chrome 83.0 | Working
macOS High Sierra v10.13.6 | 2.5 GHz Intel Core i5 | ATI Radeon HD 6750M [512 MB] | Chrome 83.0 | Working

It seems to be processor related?

**Comment by VickyXXXXXX** [comment] 2020-06-24 18:18
For low end devices, changing `this.handleChange = throttleIdleTask(this.handleChange.bind(this))` to `this.handleChange = this.handleChange.bind(this)` in search.js would solve this issue.

**Comment by naxxateux** [comment] 2020-07-23 14:38
Same issue here. But search updates after switching to another browser tab and coming back to tab with emojimart.

**Comment by leushkin** [comment] 2020-10-10 17:45
Same. For some reason, chrome is rerendering the screen (see screenshots below) and browser doesn't have enough idle time to call `requestIdleCallback` which uses for search throttling, that's why searching isn't working. I did some investigations about it, and i came to the conclusion that this is a chrome bug. 

I copy pasted some sections of emojis for exaggeration
<img width="1205" alt="Screen Shot 2020-10-10 at 18 39 35" src="https://user-images.githubusercontent.com/26031322/95659226-3d4d3700-0b28-11eb-944e-675026acc589.png">
and then i took performance metrics using chrome-dev-tools performance tab. The results wasn't good
<img width="650" alt="Screen Shot 2020-10-10 at 19 22 48" src="https://user-images.githubusercontent.com/26031322/95661003-74c1e080-0b34-11eb-9f98-b7a4d1423f0e.png">
Surprisingly safari didn't do any repaints/relayouts.
<img width="974" alt="Screen Shot 2020-10-10 at 19 33 17" src="https://user-images.githubusercontent.com/26031322/95660308-a4bab500-0b2f-11eb-94d5-a11154ce4db7.png">
It was the fist clue that it was chrome bug. After some googling i found this issue https://bugs.chromium.org/p/chromium/issues/detail?id=814439 it closed but seems like that its time to reopen it. I downloaded and tried on my PC the example page `layer-overflow.html` which attached to the issue and the bug was reproducible! (By the way in safari it works fine).
I didn't found any `overflow: hidden` but i found `overflow-y: scroll` property on `emoji-mart-scroll` class, and i tried to remove this prop, look what i got.
<img width="655" alt="Screen Shot 2020-10-10 at 19 51 14" src="https://user-images.githubusercontent.com/26031322/95661055-de41ef00-0b34-11eb-9ee7-1114eca3e9e9.png">
For some reason performance became much better! But just removing `overflow-y: scroll` isn't good solution am i right? I read somewhere that position/transition/z-index etc css rules cause reflow/relayout processes, so i removed `z-index` and `position` rules from `.emoji-mart-category .emoji-mart-emoji span` selector, also removed `position` prop from `.emoji-mart-emoji` selector. These styles are needed to draw a round gray background when hovering over emoji. Here the result:
<img width="655" alt="Screen Shot 2020-10-10 at 20 05 28" src="https://user-images.githubusercontent.com/26031322/95661485-670e5a00-0b38-11eb-9b06-61ae0dcd41d2.png">
Pretty satisfying isn't it? So for my project i decided to override position/index properties, and make the circle behind the emoji simply by setting to the button `border-radius` and `background: grey` which applies when button is hovered.

PS of course it could be fixed with replacing `requestIdleCallback` condition with just `setTimeout` at `src/utils/index.js:249`, but I am not sure that this repo is still alive and there is a chance that your pr would never be merged =(

**Comment by naxxateux** [comment] 2020-10-13 14:34
Hey @leushkin, amazing research with fascinating results! Overrided my emojimart styles too and all is working like a charm. Even hovering process is faster now! Thank you for your detailed answer.

**Comment by EtienneLem** [comment] 2020-10-13 14:43
Very interesting, thank you! Will definitely look into this to improve performance.

**Comment by matthewrobb** [comment] 2020-10-21 00:10
@leushkin Thanks for the research!

Today I was able to fix this issue by setting `will-change: unset;` on `.emoji-mart-scroll`.

**Comment by JCMais** [comment] 2022-03-02 22:59
Looks like this is still an issue, I am getting it randomly with some e2e tests.

**Comment by EtienneLem** [comment] 2022-07-27 15:16
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Closed by EtienneLem** 2022-07-27 15:16 UTC
