### ISSUE TITLE
UI Break on 13-inch mac Chrome

### ISSUE THREAD

**Issue by li6834300** [missive/emoji-mart#345] opened 2019-05-24 06:59 UTC
Please see the attachment: 
The UI of Search box break on 13-inch Mac Chrome
System: MacBook Pro (Retina, 13-inch, Early 2015), MacBook Pro (Retina, 13-inch, Mid 2015)
10.12 (16A323), macOS Sierra
Chrome Version: Version 67.0.3396.99 (Official Build) (64-bit)
(It still exists even I update Chrome Version)

![B4F1FC7EF87B8772A721630D775F0476](https://user-images.githubusercontent.com/1820864/58308437-2ffcb300-7e34-11e9-9b72-77a7e4e6dc13.jpg)

**Comment by nolanlawson** [comment] 2019-06-29 15:13
I can't reproduce on Chrome 75 on a 13-inch screen using the storybook or missive.github.io/emoji-mart.

Maybe it's because Chrome 67 is quite old?

Also, when you say "break," what do you mean? Are you referring to the search box overflowing on the right? Or are you referring to the existence of a horizontal scroll bar? Note that you can customize the number of emoji on each row.

**Comment by li6834300** [comment] 2019-07-16 07:46
Hi Thanks @nolanlawson for answering
Are you using the Mac system: MacBook Pro (Retina, 13-inch, Early 2015)
We updated Chrome to new version, it still exists. 
The 'break' refer to he overflowing of the search box. Thanks

**Comment by iamsaksham** [comment] 2019-09-04 06:40
Hi @li6834300 
Even I'm not able to replicate this issue.
I have Macbook Pro (Retina, 13-inch)

Looks like some css might be with `!important` in your code, so it might be taking your custom CSS and overriding the default CSS.
From what I see, there might be some `min-width: **px !important` in your code.
Can you inspect the input box and show all the CSS applied to it.

**Comment by iamsaksham** [comment] 2019-09-04 06:41
Hi @li6834300 
Even I'm not able to replicate this issue.
I have Macbook Pro (Retina, 13-inch)

Looks like some CSS might be with `!important`, so it might be taking the custom CSS and overriding the default CSS.
From what I see, there might be some `min-width: **px !important`.
Can you inspect the input box and show all the CSS applied to it.

**Comment by auek** [comment] 2019-09-11 09:44
I had the exact same issue and it occurred because of an outdated `normalize.css` rule. It seems like they fixed it [here](https://github.com/necolas/normalize.css/commit/fe567632afcf8afcf17925ab2a507ed87504cce8) by removing `box-sizing: content-box;` from `input[type="search"]` and that worked for me as well.

Good luck!

**Comment by nolanlawson** [comment] 2019-12-21 18:30
Thanks, since this seems due to external CSS, I'll close this issue.

**Closed by nolanlawson** 2019-12-21 18:30 UTC
