### ISSUE TITLE
Alignment in Frequently Used

### ISSUE THREAD

**Issue by AFKSanty** [missive/emoji-mart#313] opened 2019-03-22 08:27 UTC
Hey Guys,
I'm facing this weird issue where the emoticon alignment gets messed up in frequently used section whenever I spam click on them. 
Code -

```jsx
addEmoji = e => {
    console.log(localStorage.getItem('emoji-mart.frequently'));
    if (e.unified.length <= 5) {
      let emojiPic = String.fromCodePoint(`0x${e.unified}`);
      console.log(emojiPic);
    }
  };
<Picker onSelect={this.addEmoji} />
```
Take a look at the recording - https://i.imgur.com/Z9Xqppu.gif
Console logs - https://i.imgur.com/m9oQ2QF.png

**Comment by nolanlawson** [comment] 2019-03-22 22:11
Which browser?

**Comment by AFKSanty** [comment] 2019-03-23 06:00
chrome

**Comment by AFKSanty** [comment] 2019-03-23 06:03
> Which browser?

chrome

**Comment by nolanlawson** [comment] 2019-03-23 16:09
I can't reproduce in either Chrome or Firefox using the Storybook: https://missive.github.io/emoji-mart/

Can you provide a working example to demonstrate? Is there a special configuration you're using to cause this?

**Comment by AFKSanty** [comment] 2019-03-26 03:48
> I can't reproduce in either Chrome or Firefox using the Storybook: https://missive.github.io/emoji-mart/
> 
> Can you provide a working example to demonstrate? Is there a special configuration you're using to cause this?

The code snippet that you see in my first post is all the code that I have in my component. Also I noticed the issue doesnt occur on firefox for me, but it still persists on chrome. Earlier I had a piece of code which cleared the things in 'emoji-mart.frequently' and updated it with the custom emojis I have, but this code is commented out now. Do you think this has some kind of effect on the frequently used section?

**Comment by AFKSanty** [comment] 2019-03-30 10:29
@nolanlawson Any updates? Im waiting on your response to figure out this issue.

**Comment by nolanlawson** [comment] 2019-03-31 16:09
@AFKSanty I still cannot reproduce, using Chrome 73 on Ubuntu.

I've taken your code and turned it into a storybook for testing: https://github.com/missive/emoji-mart/commit/e7fd919154d6cae2635133cbeb9480065f05f9ff. You can test that with our storybook by running `yarn start` and `yarn storybook` in two separate tabs and then opening up `localhost:6006`.

Perhaps you added some custom CSS that is causing the issue?

**Comment by EtienneLem** [comment] 2022-07-27 15:36
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Closed by EtienneLem** 2022-07-27 15:36 UTC
Labels: bug
