### ISSUE TITLE
Runtime error says `D.latestVersion is not a function` in production build by Next.js 13 App Router.

### ISSUE THREAD

**Issue by Innei** [missive/emoji-mart#849] opened 2023-07-21 03:28 UTC
In the prod build, I can't open the emoji picker, and it throws an error. The information is below.

```
module.js:781 Uncaught (in promise) TypeError: D.latestVersion is not a function
    at Q (module.js:781:1)
    at Z (module.js:728:1)
    at eQ.connectedCallback (module.js:2918:1)
    at new ep (module.js:1296:1)
    at new ef (module.js:1316:1)
    at new eQ (module.js:2925:1)
    at EmojiPicker.tsx:28:9
```

The source trace is:

![CleanShot 2023-07-21 at 11 24 46@2x](https://github.com/missive/emoji-mart/assets/41265413/551f44c2-9e9b-4895-9a79-215cdb481f2e)

And my code wrote:

```tsx
({ onEmojiSelect }) => {
  const { data, isLoading } = useQuery({
    queryKey: ['emoji-data'],
    queryFn: () =>
      fetch('https://cdn.jsdelivr.net/npm/@emoji-mart/data', {
        next: {
          revalidate: 60 * 60 * 24 * 7,
        },
      }).then((response) => response.json()),

    staleTime: Number.POSITIVE_INFINITY,
  })
  const handleSelect = useCallback((emoji: any) => {
    return onEmojiSelect(emoji.native)
  }, [])

  const handleDivRef = (divEl: HTMLDivElement) => {
    import('emoji-mart').then(
      (m) =>
        new m.Picker({
          ref: {
            current: divEl,
          },
          data,
          onEmojiSelect: handleSelect,
          maxFrequentRows: 0,
        }),
    )
  }

  if (isLoading)
    return (
      <Loading className="flex h-[435px] w-[352px] rounded-md bg-slate-100 center dark:bg-neutral-800" />
    )

  return (
    <div className="w-[352px]">
      <div ref={handleDivRef} />
    </div>
  )
}
```

That's not work.

And uses `emoji-mart/react` like this:

```tsx
(({ onEmojiSelect }) => {
  const { data, isLoading } = useQuery({
    queryKey: ['emojidata'],
    queryFn: () =>
      fetch('https://cdn.jsdelivr.net/npm/@emoji-mart/data', {
        next: {
          revalidate: 60 * 60 * 24 * 7,
        },
      }).then((response) => response.json()),

    staleTime: Infinity,
  })
  const handleSelect = useCallback((emoji: any) => {
    return onEmojiSelect(emoji.native)
  }, [])
  if (isLoading) return <Loading className="w-[352px]" />

  return <Picker data={data} onEmojiSelect={handleSelect} />
})
```

Also not work in prod.

**Comment by kirkegaard** [comment] 2023-07-21 12:18
I have the same issue and created a basic sandbox of whats going on https://codesandbox.io/p/sandbox/elated-lake-m6hgwd

It seems to only break in production builds when used with nextjs

**Comment by Alex-ray** [comment] 2023-07-21 14:18
I'm encountering the same issue with `"next": "13.4.10"` and `"emoji-mart": "^5.5.2"`

**Comment by hoseinkord** [comment] 2023-07-22 04:39
I'm encountering the same issue with "next": "13.2.4" and "emoji-mart": "^5.5.2"

Uncaught (in promise) TypeError: O.latestVersion is not a function

**Comment by Bravemobin** [comment] 2023-07-22 04:42
I'm have Error too on "next:"13.4.8" and "emoji-mart": "^5.5.2"

**Comment by milo-** [comment] 2023-07-22 16:23
Also seeing the same thing

**Comment by Xhale1** [comment] 2023-07-24 17:20
Saw the same thing when upgrading to next 13.4.9 in the traditional pages router (not the new app router)

**Comment by hoseinkord** [comment] 2023-07-25 06:20
@EtienneLem

**Comment by Alex-ray** [comment] 2023-07-26 22:03
I'm also using the traditional pages router

**Comment by stevenaanen** [comment] 2023-07-27 11:06
Same issue after upgrading React this week - only in production. Latest version of both React & emoji-mart 😢

**Comment by donaldboulton** [comment] 2023-08-01 06:21
You might try dynamic imports, so it will not be bundled. Like.
`
import dynamic from 'next/dynamic'

const Picker = dynamic(
  () => import('emoji-mart'),
  { ssr: false }
)`

at : [NextJs Dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by stevenaanen** [comment] 2023-08-03 12:23
> You might try dynamic imports, so it will not be bundled. Like. ` import dynamic from 'next/dynamic'
> 
> const Picker = dynamic( () => import('emoji-mart'), { ssr: false } )`
> 
> at : [NextJs Dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import)

Tried this solution, not working for me, same result. :(

**Comment by luantrasel** [comment] 2023-08-04 21:08
Just adding `swcMinify: false` on next.config.js as @tehseenc mentioned fixed the problem

**Comment by lorypelli** [comment] 2023-08-10 07:12
> Just adding `swcMinify: false` on next.config.js as @tehseenc mentioned fixed the problem

It didn't worked for me

**Comment by lorypelli** [comment] 2023-08-10 07:23
As mentioned...I have the same issue...You can see the code at https://github.com/lorypelli/text-editor-online then go to src/app/components/Textarea.tsx

**Comment by NguyenAnhKietUIT** [comment] 2023-09-17 17:40
> Just adding `swcMinify: false` on next.config.js as @tehseenc mentioned fixed the problem

I used it but it still didn't help much

**Comment by brandalx** [comment] 2023-10-03 02:04
same

**Comment by PopDaph** [comment] 2023-10-03 09:25
Hi 👋🏻 
What fixed it for me is bumping to `"next": "^13.5.4"`.

**Comment by sirreal** [comment] 2023-10-03 12:14
This was caused by a problem in @swc/core that was [fixed in version 1.3.72](https://github.com/swc-project/swc/blob/main/CHANGELOG.md#1372---2023-07-28).

Issue: https://github.com/swc-project/swc/pull/7702

If you're using SWC, make sure you're on a recent version of @swc/core with a command like:

```sh
yarn up -R @swc/core
```

**Comment by Frying7415** [comment] 2023-11-17 11:15
Same issue for me. Runtime TypeError: O.latestVersion is not a function.
![image](https://github.com/missive/emoji-mart/assets/122051722/60a507b8-ea8f-403d-9ed6-9e0817f64e9f)
Next.js 13.4.10, emoji-mart 5.5.2
Not using SWC, so the `swcMinify: false` fix did nothing to help.
Would be grateful for any help with this issue.

**Comment by Princebhan** [comment] 2024-03-18 18:40
thanks a lot bro @tehseenc that solution is worked 🤙🏻

**Comment by hernancito** [comment] 2024-08-22 22:27
Hi! I updated to `next 13.5.6` and it started working (using Pages Router)

**Closed** 2024-08-23 12:53 UTC
