### ISSUE TITLE
Recently Used list is not updated

### ISSUE THREAD

**Issue by dpatra** [missive/emoji-mart#616] opened 2022-06-09 09:33 UTC
Hi Team,
The "Frequently used" / recent section is not updated. It requires a reload/refresh.

Could you suggest, how to fix this?

**Comment by charleshope** [comment] 2022-06-09 23:51
I have the same problem. I found that this issue is a duplicate of #243, but I couldn't find any docs for how to set these flags, so I tried adding `enableFrequentEmojiSort: true` to the constructor, but it didn't work.

**Comment by kainosnoema** [comment] 2022-07-15 20:37
Also having this issue. Seems as of the latest version, the `enableFrequentEmojiSort` option was removed. It only loads the `FrequentlyUsed` value once per session, requires a page reload to update it. Can someone from the team please give insight into how to fix this?

**Closed** 2022-07-27 02:20 UTC
Labels: v5, feature request

**Comment by ttytm** [comment] 2023-08-30 02:34
The issue doesn't seem to be fixed. Frequently used emojis are still only updated after loading the window.
