### ISSUE TITLE
emoji-mart picker css not loading on production rails and react app.

### ISSUE THREAD

**Issue by anasyo10** [missive/emoji-mart#461] opened 2020-10-30 13:38 UTC
I have setup a basic app for testing purposes. The emoji-mart picker css doesnt load up on the production. I have followed the documentation as it is. 

This is the repo: https://github.com/khuram95/emoji_testing
This is the herokuapp: https://emojis-testing.herokuapp.com/

Any help will be appreciated. Please don't close the Issue, if there is anything else needed than this I will provide after you comment. 

Thanks.

This is the code:

`
```
import React,{ useState } from 'react'
import { withStyles } from '@material-ui/core/styles'
import styles from './styles'
import Grid from '@material-ui/core/Grid'
import OutlinedInput from '@material-ui/core/OutlinedInput'
import InputAdornment from '@material-ui/core/InputAdornment'
import IconButton from '@material-ui/core/IconButton'
import Popover from '@material-ui/core/Popover'
import EmojiIcon from '@material-ui/icons/EmojiEmotions'
import { Picker } from 'emoji-mart'
import 'emoji-mart/css/emoji-mart.css'


const Emojis = (props) => {

  const { classes } = props
  const [emojiPopup, setEmojiPopup] = useState(false)

  const handleInputChange = (event) => {
  }

  const openEmoji = (event) => {
    setEmojiPopup(event.currentTarget);
  }

  const closeEmoji = () => {
    setEmojiPopup(null)
  }


  const addEmoji = (emoji, e) => {
    let inputRef = document.getElementById("message-input-field")
    inputRef.value = (inputRef.value+emoji.native)
  }

  const emojiTab = () => {
    return(
      <Popover
        id='emoji-popover'
        open={Boolean(emojiPopup)}
        anchorEl={emojiPopup}
        onClose={closeEmoji}
        anchorOrigin={{
          vertical: 'top',
          horizontal: 'center',
        }}
        transformOrigin={{
          vertical: 'bottom',
          horizontal: 'center',
        }}
      >
        <Grid item xs={12} className={classes.emojiContainer}>
          <Picker
            native
            theme='dark'
            onSelect={(emoji, e) => addEmoji(emoji,e)}
          />
        </Grid>
      </Popover>
    )
  }

  return (
    <Grid item xs={12} className={classes.inputMessageContainer}>
      <OutlinedInput
        autoFocus
        fullWidth
        multiline
        rowsMax="10"
        id="message-input-field"
        labelWidth={70}
        notched={false}
        onKeyDown={(event) => handleInputChange(event)}
        placeholder={`message in`}
        classes={{
          root: classes.inputRoot,
          notchedOutline: classes.outlinedInput
        }}
        endAdornment={
          <InputAdornment position="end">
            <IconButton
              aria-describedby='emoji-popover'
              onClick={openEmoji}
              edge="end"
            >
              <EmojiIcon />
            </IconButton>
          </InputAdornment>
        }
      />
      {emojiTab()}
    </Grid>
  );
}

export default withStyles(styles)(Emojis)

````

**Comment by EtienneLem** [comment] 2020-10-30 13:54
I don’t think your `import 'emoji-mart/css/emoji-mart.css'` does anything, or maybe your Rails isn’t configured correctly. You could try requiring the CSS file in your `application.css`. There seems to be many ways to do that, you can search for “rails require css from node_modules” on Google. We cannot provide help with that, StackOverflow would be a better place for this kind of support.

Closing the issue as this is not an issue with the library, this is a Rails misconfiguration problem. You can still add comments even if the issue is closed.

**Closed by EtienneLem** 2020-10-30 13:54 UTC

**Comment by anasyo10** [comment] 2020-10-30 16:14
As I mentioned above in the issue, if you need anything then you can just comment and I will answer to that, I have tried to add the css manually, the rails configuration is correct I have done changes to it as much as I could and it doenst add the css. Before closing the issue atleast let someone with some knowledge to comment if you have no idea about it. I provided the github repo and the code in the previous issue I had opened even if you asked there I would have commented and given you all the info that you needed. Your not "thinking" won't help me out with this. If there is something good here to use let it be good dont dismiss it by your "thinking"

**Comment by EtienneLem** [comment] 2020-10-30 16:32
Sorry, we can’t help with issues that are external to this library. You need to figure out how to include an external CSS stylesheet to your Rails app. You would have the same issue if you were using any other library that also provided a CSS stylesheet for you to include.

> the rails configuration is correct I have done changes to it as much as I could and it doenst add the css.

If that were the case, the styles would be loaded. They’re not. This points to a misconfiguration of Rails, or a wrong way to import the styles. I’m no Rails expert, but I believe Rails is configured with Webpack under the hood. You might need to add a loader to inject CSS properly. 

If you were to create a test library with a CSS file and add it to your dependencies (you can link it to a GitHub repo, you don’t have to publish an actual package), chances are importing the CSS would have the same result.

> Before closing the issue atleast let someone with some knowledge to comment if you have no idea about it.

Sorry if you’re offended by the issue being closed, but it is not an issue with this library. There’s nothing we can do or change on our end that would fix this.

As a last resort solution if you can’t find any info on how to import CSS files from a node module, you could download the stylesheet locally and add it to your `vendor` or copy/paste its content directly into your own stylesheets. Styles would need to be manually updated if you update the library. That would be less than ideal, I’m sure you can figure out how to import it from node_modules.

A support forum with people with Rails experience would be a better place to have a better answer.
