### ISSUE TITLE
Emojis misaligned in Safari

### ISSUE THREAD

**Issue by reverie** [missive/emoji-mart#476] opened 2021-01-13 16:09 UTC
Safari 14.0.2 on macOS 11.1. Works fine in Chrome.

Seeing issues like this throughout the emoji list:
![image](https://user-images.githubusercontent.com/73446/104478016-c93f8680-558f-11eb-86f3-3a2f250fbf40.png)

![image](https://user-images.githubusercontent.com/73446/104478033-ccd30d80-558f-11eb-97b0-e691f759b286.png)

**Comment by takayukioda** [comment] 2021-01-31 10:33
I'm guessing this is caused by special character `\uFE0F`, which defined as [variation selector](https://emojipedia.org/variation-selector-16).
> An invisible codepoint which specifies that the preceding character should be displayed with emoji presentation.

Here are some emoji definitions that are misaligned. All of them contains `\uFE0F` in its definitions.
☺️ https://emojipedia.org/smiling-face
☹️ https://emojipedia.org/frowning-face
☠️ https://emojipedia.org/skull-and-crossbones

**Comment by takayukioda** [comment] 2021-01-31 13:16
Oh, I found the reason.
When `word-wrap: break-word;` is set it breaks word even if it's invisible zero length character.

<img width="986" alt="スクリーンショット 2021-01-31 22 05 17" src="https://user-images.githubusercontent.com/1546410/106384868-8c3d1600-6410-11eb-8183-6d2a1fe7c355.png">
<img width="985" alt="スクリーンショット 2021-01-31 22 05 25" src="https://user-images.githubusercontent.com/1546410/106384873-93fcba80-6410-11eb-979b-75c6ba6db158.png">

**Comment by wmadden** [comment] 2021-02-09 16:26
I'm experiencing this issue too. `break-word` doesn't have any effect for me

**Comment by EtienneLem** [comment] 2022-07-27 15:08
Chances are this is fixed in latest version. Please reopen an issue if that’s not the case.

**Closed by EtienneLem** 2022-07-27 15:08 UTC
