### ISSUE TITLE
Crash on ipad/macbook

### ISSUE THREAD

**Issue by leoliu** [missive/emoji-mart#145] opened 2017-11-20 00:04 UTC
Oddly it can crash on my iPad with the following stacktrace:

![emoji crash](https://user-images.githubusercontent.com/406907/32997310-43557454-cdc9-11e7-96e2-8f22f340041f.png)

I am using the Picker component like this:
```
    <Picker
      native
      emoji="smiley"
      title=""
      i18n={{ categories }}
      sheetSize={32}
      showPreview={false}
   />
```

**Comment by leoliu** [comment] 2017-11-20 00:10
Crash on Safari on iPad and Macbook air. iPad is running the latest software. Macbook air is running 10.12.6. iPhone running the latest software doesn't crash.

**Comment by EtienneLem** [comment] 2017-11-20 14:10
What’s Emoji Mart version? Is it older than `v2.1.2`? Sounds like an issue that’s been resolved in newer versions.

**Comment by leoliu** [comment] 2017-11-20 14:53
I added it to my project yesterday and the entry in package.json is `"emoji-mart": "^2.2.1"`.

**Comment by EtienneLem** [comment] 2017-11-21 03:36
Can you tell me what’s the result of `localStorage["emoji-mart.frequently"]` in the console?

**Comment by leoliu** [comment] 2017-11-21 14:21
When crash:

```
localStorage["emoji-mart.frequently"]
undefined
```

When no crash:

```
localStorage["emoji-mart.frequently"]
"{"+1":25,"grinning":12,"kissing_heart":13,"heart_eyes":7,"laughing":7,"stuck_out_tongue_winking_eye":7,"sweat_smile":7,"joy":12,"scream":1,"flag-tk":7,"flag-ug":1,"pensive":1,"worried":7,"hushed":6,"flushed":1,"star_of_david":4,"wheel_of_dharma":2,"star_and_crescent":4,"u6e80":11,"goal_net":1,"nauseated_face":2,"goat":2,"beer":2,"latin_cross":1,"sparkling_heart":2,"owl":1,"crab":1,"octopus":1,"pig2":1,"candle":2,"stuck_out_tongue":6,"relaxed":5,"dizzy_face":7,"yum":7,"kissing_smiling_eyes":1,"kissing_closed_eyes":13,"slightly_smiling_face":1,"innocent":6,"grin":11,"woman-bowing":1,"couple":2,"bow_and_arrow":12,"clown_face":18,"money_mouth_face":5,"rolling_on_the_floor_laughing":2,"blush":2,"confused":2,"slightly_frowning_face":1,"sob":6,"drooling_face":1,"cry":1,"fearful":1,"smiley_cat":6}"
```

**Comment by nolanlawson** [comment] 2019-03-08 03:06
Is the browser in private browsing mode or some other setting to disable localStorage?

**Comment by nolanlawson** [comment] 2019-03-16 23:09
This looks like a duplicate of https://github.com/missive/emoji-mart/issues/201 which is fixed now. Please reopen if I'm incorrect.

**Closed by nolanlawson** 2019-03-16 23:09 UTC
Labels: bug

**Comment by L53c** [comment] 2022-02-01 14:49
Unfortunately I am having the same issue with version "emoji-mart": "^3.0.1", it crash my app, freezing my browser
